name: Make Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Build release APK
        run: bash ./gradlew build --stacktrace
      - name: Run LS
        run: ls $GITHUB_WORKSPACE/build/outputs/apk/debug && ls $GITHUB_WORKSPACE/build/outputs/apk/release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/build/outputs/apk/release/pandoroid-arm64-v8a-release-unsigned.apk
            ${{ github.workspace }}/build/outputs/apk/release/pandoroid-armeabi-v7a-release-unsigned.apk
            ${{ github.workspace }}/build/outputs/apk/release/pandoroid-mips-release-unsigned.apk
            ${{ github.workspace }}/build/outputs/apk/release/pandoroid-mips64-release-unsigned.apk
            ${{ github.workspace }}/build/outputs/apk/release/pandoroid-universal-release-unsigned.apk
            ${{ github.workspace }}/build/outputs/apk/release/pandoroid-x86-release-unsigned.apk
            ${{ github.workspace }}/build/outputs/apk/debug/pandoroid-arm64-v8a-debug.apk
            ${{ github.workspace }}/build/outputs/apk/debug/pandoroid-armeabi-v7a-debug.apk
            ${{ github.workspace }}/build/outputs/apk/debug/pandoroid-mips-debug.apk
            ${{ github.workspace }}/build/outputs/apk/debug/pandoroid-mips64-debug.apk
            ${{ github.workspace }}/build/outputs/apk/debug/pandoroid-universal-debug.apk
            ${{ github.workspace }}/build/outputs/apk/debug/pandoroid-x86-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}